const produtos = [
{
    id_produto: 1,
    descricao_produto: "Placa de Vídeo Intel B580",
    caminho_da_imagem: "../imagens/b580.png",
    valor_unitario: 1999.90,
    id_secao: 1,
    nome_secao: "Intel",
},
{
    id_produto: 2,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 3060 8GB",
    caminho_da_imagem: "../imagens/rtx 3060 8gb.png",
    valor_unitario: 1889.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 3,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 2060",
    caminho_da_imagem: "../imagens/rtx2060.png",
    valor_unitario: 1349.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 4,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 2070",
    caminho_da_imagem: "../imagens/rtx2070.png",
    valor_unitario: 1849.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 5,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 2080",
    caminho_da_imagem: "../imagens/rtx2080.png",
    valor_unitario: 2149.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 6,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 3050",
    caminho_da_imagem: "../imagens/rtx3050.png",
    valor_unitario: 1149.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 7,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 3070",
    caminho_da_imagem: "../imagens/rtx3070.png",
    valor_unitario: 2549.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 8,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 3080",
    caminho_da_imagem: "../imagens/rtx3080.png",
    valor_unitario: 3009.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 9,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 4060",
    caminho_da_imagem: "../imagens/rtx4060.png",
    valor_unitario: 3399.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 10,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 4070",
    caminho_da_imagem: "../imagens/rtx4070.png",
    valor_unitario: 5399.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 11,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 4080",
    caminho_da_imagem: "../imagens/rtx4080.png",
    valor_unitario: 8590.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 12,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 4090",
    caminho_da_imagem: "../imagens/rtx4090.png",
    valor_unitario: 13099.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 13,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 5050",
    caminho_da_imagem: "../imagens/rtx5050.png",
    valor_unitario: 1989.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 14,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 5060",
    caminho_da_imagem: "../imagens/rtx5060.png",
    valor_unitario: 2239.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 15,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 5070",
    caminho_da_imagem: "../imagens/rtx5070.png",
    valor_unitario: 6099.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 16,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 5080",
    caminho_da_imagem: "../imagens/rtx5080.png",
    valor_unitario: 11399.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 17,
    descricao_produto: "Placa de Vídeo NVIDIA RTX 5090",
    caminho_da_imagem: "../imagens/rtx5090.png",
    valor_unitario: 39999.90,
    id_secao: 2,
    nome_secao: "NVIDIA",
},
{
    id_produto: 18,
    descricao_produto: "Placa de Vídeo AMD RX 7600",
    caminho_da_imagem: "../imagens/rx7600.png",
    valor_unitario: 1499.90,
    id_secao: 3,
    nome_secao: "AMD",
},
{
    id_produto: 19,
    descricao_produto: "Placa de Vídeo AMD RX 9060",
    caminho_da_imagem: "../imagens/rx9060.png",
    valor_unitario: 2099.90,
    id_secao: 3,
    nome_secao: "AMD",
},
{
    id_produto: 20,
    descricao_produto: "Placa de Vídeo AMD RX 9070",
    caminho_da_imagem: "../imagens/rx9070.png",
    valor_unitario: 3999.90,
    id_secao: 3,
    nome_secao: "AMD",
},
]

export{produtos}